### ISSUE TITLE
Can you create a similar solution than runs on Blazor instead of Bridge?

### ISSUE THREAD

**Issue by YandyZaldivar** [samuelGrahame/ClassicForms#3]
https://blazor.net/

https://github.com/aspnet/Blazor

**Comment by samuelGrahame** [comment]
Hey i was thinking about that, i will need to download blazor for visual studio 2017. haven't played around with it.

looks like very interesting tech

**Comment by YandyZaldivar** [comment]
Ok, when you have it working make a post on Blazor to know what the community think.

**Comment by samuelGrahame** [comment]
I have started it.

https://github.com/samuelGrahame/ClassicFormsBlazor

I managed to get ClassicForms to build.

Accessing Js objects, etc HTMLElements are so strange in Blazor.

got simple events to work. but need to add mouseevents etc.

![image](https://user-images.githubusercontent.com/13449963/41819789-fa87d870-7809-11e8-80fc-93b036331576.png)

this is what i have working so far ^

**Comment by YandyZaldivar** [comment]
That's a very good start.

Instead of two separates projects, you could create some common interfaces and use conditional compilation. Maintaining different code bases is more difficult, specially for the core libraries. I read somewhere Bridge is going to allow to create base .NET Core projects as well as regular .NET Framework libraries.

**Comment by samuelGrahame** [comment]
Yeah I can't wait for support for. NET core for bridge. I just made a sperate project, wasnt sure how much code I needed to change. Also first time playing with blazor.

**Comment by samuelGrahame** [comment]
Im trying to get the event for window.onmousemove and onmouseup, they seem not to work atm

**Comment by samuelGrahame** [comment]
yeah i will need to wait, as there seems to be an issue with invoking multiple methods from js to c#

**Comment by samuelGrahame** [comment]
Good Afternoon

I have completed the conversion.
I have also made a Nuget Package for Blazor ClassicForms.
I am using a Shared Project for both bridge and Blazor.

![image](https://user-images.githubusercontent.com/13449963/42407744-9edc320a-8204-11e8-96cb-2e99df45f9db.png)

I also fixed the bugs regarding mouse movement.

**Comment by YandyZaldivar** [comment]
Excellent!

Next steps would be to list all supported controls or not supported controls, the shortest of them, and add the completion percent of each individual component. Other features related to the windows forms environment could also be listed, what works, what doesn't.

In the readme page you have to be more explicit on the goal of this project and the problem it solves:

**Compile and Run your Windows Forms applications on the browser.**

Other comments as the history of ExpressCraft or how you get to the conclusion of the best design do not "add".

Make a template project that average people can easily start with (Visual Studio Extension). Make a post about your solution in a few key places and wait for support and contribution.

**Comment by samuelGrahame** [comment]
will working on all that
